### ISSUE TITLE
Extrasタブで画像をアップスケールした時にエラー

### ISSUE THREAD

**Issue by Hamken100per** [bbc-mc/sdweb-eagle-pnginfo#9]
アップスケールした画像には、promptなどの情報が含まれていないので不具合を起こしているように思います。
以下、エラー時のトレースバックです。

webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/script_callbacks.py", line 159, in image_saved_callback
webui-docker-auto-1  |     c.callback(params)
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/sdweb-eagle-pnginfo/scripts/eagle-pnginfo.py", line 49, in on_image_saved
webui-docker-auto-1  |     pos_prompt = params.p.prompt
webui-docker-auto-1  | AttributeError: 'NoneType' object has no attribute 'prompt'

**Comment by takakino** [comment]
Python のことはありませわからないのですが、 49行目からを以下のような修正したらとありえず動きました。


```python
        if params is not None and params.p is not None:
            pos_prompt = params.p.prompt
            neg_prompt = params.p.negative_prompt
        else:
            pos_prompt = ""
            neg_prompt = ""
```

PRを送る自信がありませんので共有だけします。よければ修正を検討お願いします。
